name: lint

on: [pull_request]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
